"""
Extractor for the "Green Crab AI 2026" collection.

The 2026 photos are organized under ``Green Crab AI Photo Database/`` with
**self-describing filenames**, e.g.::

    052926_JEL_A_A1_Dorsal.jpeg      -> 2026-05-29, condo JEL-A, cell A1, dorsal
    052926_JEL_A_A1_Ventral_1.jpeg   -> ventral view, seq 1
    052926_JEL_A_A1_Seam_2.jpeg      -> molt-seam close-up
    060126_JEL_B_C4_Molt.jpeg        -> molt close-up

This is a reliable ground-truth alignment, so we parse condo + cell + view + date
straight from the filename and join to the condo data sheet
(``Green Crab AI Data Sheets/Green Crab AI Condo Data Sheet.xlsx``) by
(condo, cell). The sheet is laid out in three 36-row blocks — JEL-A (rows 1-36),
JEL_B (37-72), JEL_C (73-108) — with only the first row of each block naming the
condo; we assign the condo block-correctly.

Special folders:
- ``Red Crabs/`` -> ``color_state = red_green_crab`` (no cell).
- ``In Situ Crabs/`` -> ``is_in_situ = true`` (no cell).
- flat top-level ``IMG_*.jpeg`` -> unsorted camera originals; kept as a complete
  inventory but not cell-mapped.

NOTE ON OCR: the labels here come from the typed condo data sheet + the filename
convention. The photographed *paper notebook* pages are NOT on disk in this
collection (only the typed .xlsx ships in the album). Reconciling the xlsx
against the original notebooks requires those page images, which come from the
shared Apple Photos album — see tools/sync_photos_album.py.
"""

from __future__ import annotations

import csv
import re
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional, Tuple

from ..config import RAW_DIR, REPO_ROOT, YearConfig
from ..records import ImageRecord, normalize_str
from .base import iter_images, make_relpath

#: Vision-OCR transcription of the photographed paper-notebook pages. This is a
#: curated artifact (a human/vision reading of IMG_3637/3638/3639.HEIC, captured
#: 2026-06-05) that cannot be regenerated by code, so it lives under data/curated
#: and is treated as a reviewable label source, NOT a pipeline output.
NOTEBOOK_TRANSCRIPTION = REPO_ROOT / "data" / "curated" / "notebook_2026-06-05_transcription.csv"

try:
    import openpyxl
    _HAVE_OPENPYXL = True
except Exception:  # pragma: no cover
    _HAVE_OPENPYXL = False

CONDO_SHEET_REL = "Green Crab AI Data Sheets/Green Crab AI Condo Data Sheet.xlsx"
PHOTO_DB_DIR = "Green Crab AI Photo Database"

# 052926_JEL_A_A1_Dorsal_1.jpeg  (date, condo letter, optional cell, optional
# view/feature token, optional sequence)
FNAME_RE = re.compile(
    r"^(?P<date>\d{6})_JEL[_-]?(?P<condo>[A-Ca-c])"
    r"(?:[_-](?P<cell>[A-Fa-f][1-6]))?"
    r"(?:[_-](?P<view>[A-Za-z]+))?"
    r"(?:[_-](?P<seq>\d+))?$"
)

VIEW_TOKENS = {"dorsal": "dorsal", "ventral": "ventral", "side": "side"}
# Non-view feature close-ups; recorded as molt indicators, view stays unknown.
FEATURE_TOKENS = {"seam", "molt", "crack", "halo"}

PHASE_MAP = {
    "intermolt": "intermolt", "early pm": "pre_molt", "mid pm": "pre_molt",
    "mid-late pm": "pre_molt", "late pm": "peeler_imminent",
    "imminent": "peeler_imminent", "molt": "molted", "molted": "molted",
    "dead": "dead",
}


def _norm_condo(text: str) -> str:
    """'JEL-A' / 'JEL_A' / 'A' -> 'JELA' for joining."""
    t = normalize_str(text).upper().replace("-", "").replace("_", "").replace(" ", "")
    if t.startswith("JEL"):
        return t
    return "JEL" + t


def _read_condo_cells() -> Dict[Tuple[str, str], Dict[str, str]]:
    """Return ``{(condo_norm, cell): rowdata}`` from the condo data sheet.

    Condo is carried forward within each 36-row block (only the block's first
    row names the condo).
    """
    path = RAW_DIR / "Green Crab AI 2026" / CONDO_SHEET_REL
    if not (_HAVE_OPENPYXL and path.exists()):
        return {}
    import warnings
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        wb = openpyxl.load_workbook(path, data_only=True)
    ws = wb.worksheets[0]
    rows = list(ws.iter_rows(values_only=True))
    header = [normalize_str(c).lower() for c in rows[0]]

    def col(name: str) -> Optional[int]:
        for i, h in enumerate(header):
            if name in h:
                return i
        return None

    idx = {
        "date_added": col("date added"), "condo": col("condo"), "cell": col("cell"),
        "phase": col("molt  phase") if col("molt  phase") is not None else col("molt phase"),
        "date_removed": col("date removed"), "outcome": col("outcome"),
        "pred_phase": col("moltmeter predictor"), "pred_days": col("predictor days"),
        "notes": col("notes"),
    }
    out: Dict[Tuple[str, str], Dict[str, str]] = {}
    last_condo = ""
    for raw in rows[1:]:
        def get(key: str) -> str:
            j = idx.get(key)
            return normalize_str(raw[j]) if j is not None and j < len(raw) else ""
        cell = get("cell").upper()
        if not cell:
            continue
        condo = get("condo")
        if condo:
            last_condo = _norm_condo(condo)
        out[(last_condo, cell)] = {
            "known_molt_phase": PHASE_MAP.get(get("phase").lower(), ""),
            "phase_text": get("phase"),
            "date_added": get("date_added")[:10],
            "date_removed": get("date_removed")[:10],
            "outcome": get("outcome"),
            "pred_phase": get("pred_phase"),
            "pred_days": get("pred_days"),
            "notes": get("notes"),
        }
    return out


def _parse_date(mmddyy: str) -> str:
    try:
        return datetime.strptime(mmddyy, "%m%d%y").strftime("%Y-%m-%d")
    except ValueError:
        return ""


def _classify_view(token: str) -> Tuple[str, str]:
    """Return (view, feature_note) for a filename view/feature token."""
    t = token.lower()
    if t in VIEW_TOKENS:
        return VIEW_TOKENS[t], ""
    if t in FEATURE_TOKENS:
        return "unknown", f"{t} close-up"
    return "unknown", ""


def _record_for(img: Path, cfg: YearConfig, cells: Dict[Tuple[str, str], Dict[str, str]]) -> ImageRecord:
    rel_parts = img.relative_to(RAW_DIR / cfg.raw_subdir).parts
    dataset = cfg.raw_subdir
    color_state = ""
    is_in_situ = "false"
    # Folder-level context.
    joined = "/".join(rel_parts).lower()
    if "red crab" in joined:
        color_state = "red_green_crab"
    if "in situ" in joined:
        is_in_situ = "true"

    m = FNAME_RE.match(img.stem)
    base = dict(
        year=cfg.sheet_name, dataset=dataset, image_relpath=make_relpath(img),
        abs_path=str(img), original_filename=img.name, color_state=color_state,
        is_in_situ=is_in_situ,
    )

    if not m:
        # Unsorted originals / non-conforming names: full inventory, no cell map.
        base.update(label_source="2026 image (unmapped filename)",
                    label_confidence="unknown",
                    source_notes="; ".join(rel_parts[:-1]))
        return ImageRecord(**base)

    date = _parse_date(m.group("date"))
    condo = _norm_condo(m.group("condo"))
    cell = (m.group("cell") or "").upper()
    view_token = m.group("view") or ""
    view, feature_note = _classify_view(view_token)

    base.update(capture_date=date, view=view)
    if not cell:
        base.update(
            crab_id=f"{condo}", session_id=f"2026::{date}",
            condo_id=condo,
            label_source="filename (condo overview, no cell)",
            label_confidence="unknown",
            source_notes=feature_note,
        )
        return ImageRecord(**base)

    info = cells.get((condo, cell))
    crab_id = f"{condo}-{cell}"
    notes_bits = [feature_note]
    if info:
        notes_bits += [
            f"sheet_phase={info['phase_text']}" if info["phase_text"] else "",
            f"moltmeter={info['pred_phase']}/{info['pred_days']}d" if info["pred_phase"] else "",
            info["notes"],
        ]
        base.update(
            known_molt_phase=info["known_molt_phase"],
            outcome=info["outcome"],
            label_source="filename + condo_sheet (condo,cell join)",
            label_confidence="high",
        )
    else:
        base.update(
            label_source="filename (no matching condo_sheet cell)",
            label_confidence="medium",
        )
    base.update(
        crab_id=crab_id, observation_id=crab_id,
        session_id=f"2026::{date}", condo_id=condo, cell_id=cell,
        source_notes="; ".join(b for b in notes_bits if b),
    )
    return ImageRecord(**base)


def _notebook_phase(note: str) -> str:
    """Conservative molt-phase inference from a handwritten molt-cue note.

    The notebook records visual cues (seam/halo/dusky), not phase names, so this
    is a best-effort mapping; the raw note is always preserved in source_notes
    and the expert columns are the authority.
    """
    n = note.lower()
    if not n:
        return ""
    if any(k in n for k in ("imminent", "molt in 1 day", "molt within", "days to molt",
                            "seam open", "seam splitting", "split starting",
                            "starting to split", "wide seam")):
        return "peeler_imminent"
    if "seam" in n or "crack" in n:
        return "pre_molt"
    if "halo" in n:
        return "pre_molt"
    return "intermolt"


def _notebook_records(cfg: YearConfig) -> List[ImageRecord]:
    """Image-less observation rows from the OCR'd paper-notebook transcription.

    Per the data owner: add rows for the notebook observations but do NOT fill in
    thumbnail/image data (there are no photos for the 6/5 session). So these rows
    carry condo/cell/date/phase/notes but leave image_relpath and abs_path empty,
    which makes the assemble stage skip the thumbnail and the predict stage skip
    model inference for them.
    """
    if not NOTEBOOK_TRANSCRIPTION.exists():
        return []
    records: List[ImageRecord] = []
    with NOTEBOOK_TRANSCRIPTION.open(newline="") as f:
        for row in csv.DictReader(f):
            condo = _norm_condo(row["condo"])
            cell = row["cell"].upper()
            note = normalize_str(row["notebook_note"])
            is_empty = normalize_str(row.get("empty")) == "1"
            date = normalize_str(row["session_date"])
            crab_id = f"{condo}-{cell}"
            src_img = normalize_str(row.get("source_image"))
            records.append(ImageRecord(
                year=cfg.sheet_name,
                dataset="Green Crab AI 2026 (paper notebook, no photo)",
                image_relpath="",            # no image -> no thumbnail
                abs_path="",                 # no image -> predict stage skips it
                crab_id=crab_id,
                observation_id=crab_id,
                session_id=f"2026::{date}",
                original_filename="",
                capture_date=date,
                known_molt_phase="" if is_empty else _notebook_phase(note),
                view="notebook_observation",
                outcome="empty_cell" if is_empty else "",
                condo_id=condo,
                cell_id=cell,
                degree_of_molt=note,          # raw molt-cue text
                label_source=f"paper notebook {date} (vision OCR, {src_img}); needs expert review",
                label_confidence="medium",
                source_notes=("empty cell (no crab present)" if is_empty else note),
                is_in_situ="false",
            ))
    return records


def extract(cfg: YearConfig) -> List[ImageRecord]:
    assert cfg.raw_subdir is not None
    root = RAW_DIR / cfg.raw_subdir
    if not root.exists():
        return []
    cells = _read_condo_cells()
    records: List[ImageRecord] = []
    for img in iter_images(root):
        if "Green Crab AI Data Sheets" in img.parts:
            continue  # the xlsx folder holds no crab images
        # The post-sync album adds ~1.5k HEIC live-photos that largely duplicate
        # the jpeg set (e.g. IMG_2543.jpeg vs "IMG_2543 (1).HEIC"). Skip HEIC as
        # image rows to avoid duplicating the sheet; the notebook HEIC are
        # captured separately via the transcription. Revisit with a content-hash
        # dedup if the HEIC-only originals are needed.
        if img.suffix.lower() == ".heic":
            continue
        records.append(_record_for(img, cfg, cells))
    # Append image-less paper-notebook observation rows (6/5 session).
    records.extend(_notebook_records(cfg))
    return records
